package at.if22b208.mtc.util.mapper;

import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

import at.if22b208.mtc.dto.card.CardDto;
import at.if22b208.mtc.entity.Card;

/**
 * The {@code CardMapper} interface is used with MapStruct to automatically generate
 * mapping code between {@link Card} and {@link CardDto} instances.
 * It defines methods for mapping a {@link Card} to a {@link CardDto} and vice versa.
 * The implementation of this interface is generated by MapStruct at compile time.
 *
 * <p>Usage:</p>
 * <pre>
 * {@code
 * CardDto cardDto = CardMapper.INSTANCE.map(card);
 * Card card = CardMapper.INSTANCE.map(cardDto);
 * }
 * </pre>
 *
 * @see Mapper
 * @see Mappers
 */
@Mapper
public interface CardMapper {
    CardMapper INSTANCE = Mappers.getMapper(CardMapper.class);

    /**
     * Maps a {@link Card} entity to a {@link CardDto}.
     *
     * @param card The {@link Card} entity to be mapped.
     * @return The corresponding {@link CardDto}.
     */
    CardDto map(Card card);

    /**
     * Maps a {@link Card} entity to a {@link CardDto}.
     *
     * @param card The {@link Card} entity to be mapped.
     * @return The corresponding {@link CardDto}.
     */
    Card map(CardDto card);
}